<?php
$title = 'Keepict - ' . $album->name;
$this->headtitle($title);
?>
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigation">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Keepict</a>
    </div>
    <div class="collapse navbar-collapse" id="navigation">
      <ul class="nav navbar-nav">
        <li><a href="/">Flux</a></li>
        <li><a href="<?= $this->url('album');?>">Albums</a></li>
      </ul>
      <?php $formSearch = $this->formSearch;
            $formSearch->setAttribute('class', 'navbar-form navbar-left');
            $formSearch->setAttribute('role', 'search');
            $formSearch->prepare(); 
            echo $this->form()->openTag($formSearch); ?> 
        <div class="form-group">
          <?php echo $this->formInput($formSearch->get('predicate')); ?>
        </div>
      <?php echo $this->form()->closeTag(); ?>
      <ul class="nav navbar-nav navbar-right">
        <li class="hidden-xs">
          <?php 
            $pattern = '/^beardfont/';
            if(preg_match_all($pattern, $user->avatar)): ?>
              <div class="profil-pic-default">
                <span class="<?= $user->avatar ?>"></span>
              </div>
          <?php else: ?>
                <div class="profil-pic">
                    <img src="<?= '/' . $this->escapeHtml($user->avatar) ?>" alt="avatar">
                </div>
          <?php endif; ?>
        </li>
        <li class="dropdown" id='nav-user'>
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><?= $user->firstname . ' ' . $user->lastname ?> <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <?php if($user->isAdmin == 1): ?>
            <li><a href="<?= $this->url('album', array('action'=>'create'));?>">Créer un album</a></li>
            <li><a href="<?= $this->url('picture', array('action'=>'import', 'id' => $album->id)); ?>">Importer des photos</a></li>
            <li class="divider"></li>
            <li><a href="<?= $this->url('dashboard', array('action'=>'members'));?>">Administration <?php if($this->numPendingUser!=0): echo '<span class="label label-primary">' . $this->numPendingUser . '</span>'; endif; ?></a></li>
            <li class="divider"></li>
            <?php endif;?>
            <li><a href="<?= $this->url('account', array('action'=>'settings'));?>">Paramètres du compte</a></li>
            <li><a href="<?= $this->url('account', array('action'=>'signout'));?>">Me déconnecter</a></li>
          </ul>
        </li>
      </ul> 
    </div>
  </div>
</nav>

<div class="alert alert-danger r-click">
  <a class="close">×</a>
  <strong>Oops ! </strong>Les photos sont la propriété de l'auteur !
</div>

<div class="wrap">
  <div class="pic-img-land">
    <img src="<?= $this->escapeHtml('/'.$album->pathCover) ?>   " class="img-responsive" alt="...">
  </div>
  <div class="pic-data">
    <h2><?= $this->escapeHtml($album->name) ?></h2>
    <hr>
    <div class="row">
      <?php foreach ($this->pictures as $picture) : ?>
      <div class="col-xs-12 col-sm-3 col-md-3">
        <a href="<?= $this->url('picture', array('action'=>'index', 'id' => $picture->id, 'slug' => $picture->slug));?>" class="thumbnail">
          <img src="<?= $this->escapeHtml('/' . $picture->pathThumbnail) ?>" alt="thumbnail-<?= $this->escapehtml($picture->id)?>">
        </a>
      </div>
      <?php endforeach; ?>
    </div>
    <br>
    <?php
     echo $this->paginationControl(
         $this->pictures,
         'Elastic',
         'pagination-param',
         array(
             'route' => 'album',
             'action' => 'details',
             'id' => $this->id_album
         )
     );
     ?>
  </div>
</div>