<?php 
    $title = 'Keepict - connexion';
    $this->headtitle($title);
?>

<?php if($this->userNotAllowed === true):?>
<div class="alert alert-danger alert-login">
  <a class="close">×</a>
  <strong> Petit problème ! </strong>Vérifie tes informations de connexion !
</div>
<?php endif;?>

<div class="login">
  <div class="container">
    <?php $form = $this->form;
    $form->setAttribute('class', 'form-login');
    $form->setAttribute('role', 'form');
    $form->setAttribute('action', $this->url('account', array('action' => 'signin')));
    $form->prepare(); 
    echo $this->form()->openTag($form); ?>
    <h2>Se connecter</h2>
    <?php echo $this->form_row($form->get('csrf')); 
    echo $this->formHidden($form->get('id')); 
    echo $this->formemail($form->get('courriel'));
    echo $this->formInput($form->get('password')); ?>
    <br>
    <?php echo $this->formsubmit($form->get('submit')); ?>
    <br>
    <?php echo $this->form()->closeTag(); ?>
  </div>
</div>
