<?php echo $this->doctype(); ?>
<html lang="fr">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
        <meta name="apple-mobile-web-app-capable" content="yes">
        <?= $this->headTitle('') ?>
        <?= $this->headLink()->prependStylesheet($this->basePath() . '/css/style.css')
                             ->prependStylesheet($this->basePath() . '/css/libs/chosen.min.css')
                             ->prependStylesheet($this->basePath() . '/css/libs/datepicker.min.css')
                             ->prependStylesheet($this->basePath() . '/css/libs/fancybox.min.css')
                             ->prependStylesheet($this->basePath() . '/css/libs/bootstrap.min.css') ?>
        <!--[if lt IE 9]>
          <script src="js/libs/html5shiv.min.js"></script>
          <script src="js/libs/respond.min.js"></script>
        <![endif]-->
    </head>
    <body>
        <?= $this->content; ?>
        <?= $this->inlineScript()->prependFile($this->basePath() . '/js/main.js')
                                 ->prependFile($this->basePath() . '/js/libs/chosen.jquery.min.js')
                                 ->prependFile($this->basePath() . '/js/libs/datepicker.min.js')
                                 ->prependFile($this->basePath() . '/js/libs/jquery.fancybox-2.1.5.min.js')
                                 ->prependFile($this->basePath() . '/js/libs/bootstrap.min.js')
                                 ->prependFile($this->basePath() . '/js/libs/jquery-1.11.0.min.js') ?>
    </body>
</html>
