<?php if ($this->pageCount): ?>
 <div class="wrap-pagination">
     <ul class="pagination">
         <!-- Previous page link -->
         <?php if (isset($this->previous)): ?>
             <li>
                 <a href="<?php echo $this->url($this->route, array('action' => $action, 'id' => $id, 'page' => $this->previous)); ?>"><i class="icon-left-open"></i></a>
             </li>
         <?php else: ?>
             <li class="disabled">
                 <a href="#"><i class="icon-left-open"></i></a>
             </li>
         <?php endif; ?>

         <!-- Numbered page links -->
         <?php foreach ($this->pagesInRange as $page): ?>
             <?php if ($page != $this->current): ?>
                 <li>
                     <a href="<?php echo $this->url($this->route, array('action' => $action, 'id' => $id, 'page' => $page)); ?>">
                         <?php echo $page; ?>
                     </a>
                 </li>
             <?php else: ?>
                 <li class="active">
                     <a href="#"><?php echo $page; ?></a>
                 </li>
             <?php endif; ?>
         <?php endforeach; ?>

         <!-- Next page link -->
         <?php if (isset($this->next)): ?>
             <li>
                 <a href="<?php echo $this->url($this->route, array('action' => $action, 'id' => $id, 'page' => $this->next)); ?>"><i class="icon-right-open"></i></a>
             </li>
         <?php else: ?>
             <li class="disabled">
                 <a href="#"><i class="icon-right-open"></i></a>
             </li>
         <?php endif; ?>
     </ul>
 </div>
<?php endif; ?>