<?php 
    $title = 'Keepict - Administration';
    $this->headtitle($title);
?>

<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigation">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Keepict</a>
    </div>
    <div class="collapse navbar-collapse" id="navigation">
      <ul class="nav navbar-nav">
        <li><a href="/">Flux</a></li>
        <li><a href="<?= $this->url('album');?>">Albums</a></li>
      </ul>
      <?php $formSearch = $this->formSearch;
            $formSearch->setAttribute('class', 'navbar-form navbar-left');
            $formSearch->setAttribute('role', 'search');
            $formSearch->prepare(); 
            echo $this->form()->openTag($formSearch); ?> 
        <div class="form-group">
          <?php echo $this->formInput($formSearch->get('predicate')); ?>
        </div>
      <?php echo $this->form()->closeTag(); ?>
      <ul class="nav navbar-nav navbar-right">
        <li class="hidden-xs">
         <?php 
            $pattern = '/^beardfont/';
            if(preg_match_all($pattern, $user->avatar)): ?>
              <div class="profil-pic-default">
                <span class="<?= $user->avatar ?>"></span>
              </div>
          <?php else: ?>
                <div class="profil-pic">
                    <img src="<?= '/' . $this->escapeHtml($user->avatar) ?>" alt="avatar-<?= $this->escapeHtml($user->id) ?>">
                </div>
          <?php endif; ?> 
        </li>
        <li class="dropdown" id='nav-user'>
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><?= $user->firstname . ' ' . $user->lastname ?> <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <?php if($user->isAdmin == 1): ?>
            <li><a href="<?= $this->url('album', array('action'=>'create'));?>">Créer un album</a></li>
            <li><a href="<?= $this->url('picture', array('action'=>'import')); ?>">Importer des photos</a></li>
            <li class="divider"></li>
            <li><a href="<?= $this->url('dashboard', array('action'=>'members'));?>">Administration <?php if($this->numPendingUser!=0): echo '<span class="label label-primary">' . $this->numPendingUser . '</span>'; endif; ?></a></li>
            <li class="divider"></li>
            <?php endif;?>
            <li><a href="<?= $this->url('account', array('action'=>'settings'));?>">Paramètres du compte</a></li>
            <li><a href="<?= $this->url('account', array('action'=>'signout'));?>">Me déconnecter</a></li>
          </ul>
        </li>
      </ul> 
    </div>
  </div>
</nav>

<?php if($this->existingCategory === true):?>
<div class="alert alert-danger alert-login">
  <a class="close">×</a>
  <strong> Petit problème ! </strong>Cette catégorie existe déjà.
</div>
<?php endif;?>

<div class="wrap">
  <h2 class="settings-form-h">Importer des photos</h2>
  <?php $form = $this->form;
        $form->setAttribute('role', 'form');
        $form->setAttribute('action', $this->url('dashboard', array('action' => 'add')));
        $form->prepare(); 
        echo $this->form()->openTag($form); ?> 
    <div class="settings-form radius">
      <?php echo $this->form_row($form->get('csrf')); 
            echo $this->formHidden($form->get('id')); ?>
      <div class="form-group">
          <?php echo $this->formLabel($form->get('wording')); 
                echo $this->formInput($form->get('wording')); ?>
      </div>
      <?php echo $this->formsubmit($form->get('submit')->setValue('Créer')); ?>
      <a class="btn btn-default" href="<?= $this->url('dashboard') ?>">Annuler</a>
    </div>
  <?php echo $this->form()->closeTag(); ?>
</div>